#!/bin/bash

while read local_ref local_oid remote_ref remote_oid
do
    branch=${remote_ref##*/}
    remote_branch=`git branch -lr | grep ${branch}\$`
    test -n "$remote_branch" && continue
    if [ -z "$(grep -iE 'opw-[0-9]{7}-' <<< $branch)" ]
    then
        REPLY=1
        while test -n "$REPLY"
        do
            read -p 'No (valid) ticket ID in branch name, continue? [Y/n]' -n 1 -r < /dev/tty
            echo
            test "$REPLY" = 'n' -o "$REPLY" = 'N' && exit 1
            test "$REPLY" = 'y' -o "$REPLY" = 'Y' -o "$REPLY" = ' ' && unset REPLY
        done
    fi
    version=`grep -Eo '^(master|(saas-)?[0-9]+\.[0-9])' <<< $branch`
    if [ -n "$version" ]
    then
        case "$(git remote get-url origin | grep enterprise)" in
            '') repo=odoo;;
            *)  repo=enterprise;;
        esac
        sh -c """
            sleep 3
            open https://github.com/odoo/${repo}/compare/${version}...odoo-dev:${repo}:${branch}
        """ > /dev/null&
    fi
    #open https://github.com/odoo/${repo}/compare/${version}...odoo-dev:${repo}:${branch}?expand=1
done

exit 0
